In [9]:
import pandas as pd

In [24]:
df = pd.read_parquet("../data/raw/nulls/data.parquet")

In [18]:
df.head()

,nombre_entidad,nit_entidad,departamento,ciudad,localizaci_n,orden,sector,rama,entidad_centralizada,proceso_de_compra,...,n_mero_de_documento_supervisor,nombre_ordenador_de_pago,tipo_de_documento_ordenador_de_pago,n_mero_de_documento_ordenador_de_pago,documentos_tipo,descripcion_documentos_tipo,fecha_de_notificaci_n_de_prorrogaci_n,fecha_inicio_liquidacion,fecha_fin_liquidacion,ultima_actualizacion
0,ALCALDIA MUNICIPAL DE BAHIA SOLANO CHOCO,891680395,Chocó,Bahía Solano,"Colombia, Chocó , Bahía Solano",Territorial,Servicio Público,Ejecutivo,Centralizada,CO1.BDOS.10010097,...,No definido,No definido,No definido,No definido,False,No definido,NaT,NaT,NaT,NaT
1,"Ministerio de las Culturas, las Artes y los Sa...",830034348,Distrito Capital de Bogotá,Bogotá,"Colombia, Bogotá, Bogotá",Nacional,Cultura,Ejecutivo,Centralizada,CO1.BDOS.364191,...,No definido,No definido,No definido,No definido,False,No definido,NaT,NaT,NaT,NaT
2,ALCALDÍA DEL DISTRITO TURÍSTICO Y CULTURAL DE ...,890480184,Bolívar,Cartagena,"Colombia, Bolívar , Cartagena",Territorial,No aplica/No pertenece,Ejecutivo,Centralizada,CO1.BDOS.5431326,...,No definido,No definido,No definido,No definido,False,No definido,NaT,NaT,NaT,NaT
3,ESCUELA DE POLICIA SIMON BOLIVAR,800141336,Valle del Cauca,No Definido,"Colombia, Valle del Cauca , No Definido",Territorial,defensa,Ejecutivo,Descentralizada,CO1.BDOS.1925757,...,No definido,No definido,No definido,No definido,False,No definido,2021-09-30,NaT,NaT,NaT
4,ALCALDÍA LOCAL DE BARRIOS UNIDOS,899999061,Distrito Capital de Bogotá,Bogotá,"Colombia, Bogotá, Bogotá",Territorial,Servicio Público,Ejecutivo,Centralizada,CO1.BDOS.2254661,...,No definido,No definido,No definido,No definido,False,No definido,NaT,NaT,NaT,NaT

In [26]:
df.columns.tolist()

['nombre_entidad',
 'nit_entidad',
 'departamento',
 'ciudad',
 'localizaci_n',
 'orden',
 'sector',
 'rama',
 'entidad_centralizada',
 'proceso_de_compra',
 'id_contrato',
 'referencia_del_contrato',
 'estado_contrato',
 'codigo_de_categoria_principal',
 'descripcion_del_proceso',
 'tipo_de_contrato',
 'modalidad_de_contratacion',
 'justificacion_modalidad_de',
 'fecha_de_firma',
 'fecha_de_fin_del_contrato',
 'condiciones_de_entrega',
 'tipodocproveedor',
 'documento_proveedor',
 'proveedor_adjudicado',
 'es_grupo',
 'es_pyme',
 'habilita_pago_adelantado',
 'liquidaci_n',
 'obligaci_n_ambiental',
 'obligaciones_postconsumo',
 'reversion',
 'origen_de_los_recursos',
 'destino_gasto',
 'valor_del_contrato',
 'valor_de_pago_adelantado',
 'valor_facturado',
 'valor_pendiente_de_pago',
 'valor_pagado',
 'valor_amortizado',
 'valor_pendiente_de',
 'valor_pendiente_de_ejecucion',
 'saldo_cdp',
 'saldo_vigencia',
 'espostconflicto',
 'dias_adicionados',
 'puntos_del_acuerdo',
 'pilares_del_acuerdo',
 'urlproceso',
 'nombre_representante_legal',
 'nacionalidad_representante_legal',
 'domicilio_representante_legal',
 'tipo_de_identificaci_n_representante_legal',
 'identificaci_n_representante_legal',
 'g_nero_representante_legal',
 'presupuesto_general_de_la_nacion_pgn',
 'sistema_general_de_participaciones',
 'sistema_general_de_regal_as',
 'recursos_propios_alcald_as_gobernaciones_y_resguardos_ind_genas_',
 'recursos_de_credito',
 'recursos_propios',
 'codigo_entidad',
 'codigo_proveedor',
 'objeto_del_contrato',
 'duraci_n_del_contrato',
 'nombre_del_banco',
 'tipo_de_cuenta',
 'n_mero_de_cuenta',
 'el_contrato_puede_ser_prorrogado',
 'nombre_ordenador_del_gasto',
 'tipo_de_documento_ordenador_del_gasto',
 'n_mero_de_documento_ordenador_del_gasto',
 'nombre_supervisor',
 'tipo_de_documento_supervisor',
 'n_mero_de_documento_supervisor',
 'nombre_ordenador_de_pago',
 'tipo_de_documento_ordenador_de_pago',
 'n_mero_de_documento_ordenador_de_pago',
 'documentos_tipo',
 'descripcion_documentos_tipo',
 'fecha_de_notificaci_n_de_prorrogaci_n',
 'fecha_inicio_liquidacion',
 'fecha_fin_liquidacion',
 'ultima_actualizacion']

In [19]:
df.drop(columns = ["urlproceso"], inplace = True)

In [22]:
pd.DataFrame(dict([(col, pd.Series(df[col].unique())) for col in df]))

,nombre_entidad,nit_entidad,departamento,ciudad,localizaci_n,orden,sector,rama,entidad_centralizada,proceso_de_compra,...,n_mero_de_documento_supervisor,nombre_ordenador_de_pago,tipo_de_documento_ordenador_de_pago,n_mero_de_documento_ordenador_de_pago,documentos_tipo,descripcion_documentos_tipo,fecha_de_notificaci_n_de_prorrogaci_n,fecha_inicio_liquidacion,fecha_fin_liquidacion,ultima_actualizacion
0,ALCALDIA MUNICIPAL DE BAHIA SOLANO CHOCO,891680395,Chocó,Bahía Solano,"Colombia, Chocó , Bahía Solano",Territorial,Servicio Público,Ejecutivo,Centralizada,CO1.BDOS.10010097,...,No definido,No definido,No definido,No definido,False,No definido,NaT,NaT,NaT,NaT
1,"Ministerio de las Culturas, las Artes y los Sa...",830034348,Distrito Capital de Bogotá,Bogotá,"Colombia, Bogotá, Bogotá",Nacional,Cultura,Corporación Autónoma,Descentralizada,CO1.BDOS.364191,...,91447398,ANDREA CHACON CASTILLO,Cédula de Ciudadanía,1100959001,True,Infraestructura de transporte (interventoría d...,2021-09-30,2034-11-26,2035-03-26,2023-09-08
2,ALCALDÍA DEL DISTRITO TURÍSTICO Y CULTURAL DE ...,890480184,Bolívar,Cartagena,"Colombia, Bolívar , Cartagena",Corporación Autónoma,No aplica/No pertenece,Legislativo,NaN,CO1.BDOS.5431326,...,10770658,RAFAEL ANGEL CASTILLO PACHECO,Cédula de Extranjería,8713074,NaN,"Sector de infraestructura social (Cultura, rec...",2021-12-15,2023-12-23,2024-06-23,2025-03-03
3,ESCUELA DE POLICIA SIMON BOLIVAR,800141336,Valle del Cauca,No Definido,"Colombia, Valle del Cauca , No Definido",No Definido,defensa,Judicial,NaN,CO1.BDOS.1925757,...,1128282988,OLGA LUCIA GOMEZ HOYOS,Otro,21873758,NaN,"Convenios solidarios - Régimen artículo 95, Le...",2021-01-16,2027-01-01,2029-06-30,2025-02-28
4,ALCALDÍA LOCAL DE BARRIOS UNIDOS,899999061,Tolima,Ibagué,"Colombia, Bogotá, Bogotá",NaN,Ambiente y Desarrollo Sostenible,No Definido,NaN,CO1.BDOS.2254661,...,17421983,FEDERICO ALVIZ TRUJILLO,Citizenship Identification,16832701,NaN,Infraestructura de agua potable y saneamiento ...,2023-12-06,2026-06-30,2026-07-03,2023-08-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
423511,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaT,NaT
423512,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaT,NaT
423513,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaT,NaT
423514,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaT,NaT
423515,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaT,NaT

### Contratos duplicados

In [ ]:
import duckdb

Extracción de los IDs duplicados en toda la base de datos

In [47]:
contratos_duplicados = duckdb.query("""
    SELECT id_contrato
    FROM '../data/raw/**/*.parquet'
    WHERE id_contrato IN(
    SELECT id_contrato
    FROM '../data/raw/**/*.parquet'
    GROUP BY id_contrato
    HAVING COUNT(*) > 1
    )
""").df()['id_contrato']

In [54]:
contratos_duplicados_series = duckdb.query("""
    SELECT id_contrato
    FROM '../data/raw/**/*.parquet'
    WHERE id_contrato IN(
    SELECT id_contrato
    FROM '../data/raw/**/*.parquet'
    GROUP BY id_contrato
    HAVING COUNT(*) > 1
    )
""").df()

In [58]:
contratos_duplicados_series

            id_contrato
0    CO1.PCCNTR.9422175
1    CO1.PCCNTR.9414611
2    CO1.PCCNTR.9420206
3    CO1.PCCNTR.9460834
4    CO1.PCCNTR.9273556
..                  ...
301  CO1.PCCNTR.9458612
302  CO1.PCCNTR.9446585
303  CO1.PCCNTR.9461399
304  CO1.PCCNTR.9398556
305  CO1.PCCNTR.9460804

[306 rows x 1 columns]

In [61]:
for contrato in contratos_duplicados_series.itertuples():
    print(contrato.id_contrato)

CO1.PCCNTR.9422175
CO1.PCCNTR.9414611
CO1.PCCNTR.9420206
CO1.PCCNTR.9460834
CO1.PCCNTR.9273556
CO1.PCCNTR.9446585
CO1.PCCNTR.9420327
CO1.PCCNTR.9457332
CO1.PCCNTR.9419364
CO1.PCCNTR.9399662
CO1.PCCNTR.9422273
CO1.PCCNTR.9430135
CO1.PCCNTR.9419486
CO1.PCCNTR.9440009
CO1.PCCNTR.9457342
CO1.PCCNTR.9457779
CO1.PCCNTR.9421134
CO1.PCCNTR.9461391
CO1.PCCNTR.9422203
CO1.PCCNTR.9420325
CO1.PCCNTR.9422070
CO1.PCCNTR.9419639
CO1.PCCNTR.9413743
CO1.PCCNTR.9425884
CO1.PCCNTR.9420322
CO1.PCCNTR.9419352
CO1.PCCNTR.9422074
CO1.PCCNTR.9461265
CO1.PCCNTR.9437411
CO1.PCCNTR.9460962
CO1.PCCNTR.9460828
CO1.PCCNTR.9453901
CO1.PCCNTR.9421264
CO1.PCCNTR.9427811
CO1.PCCNTR.9436434
CO1.PCCNTR.9422479
CO1.PCCNTR.9428745
CO1.PCCNTR.9457335
CO1.PCCNTR.9453926
CO1.PCCNTR.9419849
CO1.PCCNTR.9460716
CO1.PCCNTR.9432011
CO1.PCCNTR.9420876
CO1.PCCNTR.9420406
CO1.PCCNTR.9455439
CO1.PCCNTR.9420334
CO1.PCCNTR.9420862
CO1.PCCNTR.9420314
CO1.PCCNTR.9421966
CO1.PCCNTR.9419911
CO1.PCCNTR.9435774
CO1.PCCNTR.9461324
CO1.PCCNTR.9422266
CO1.PCCNTR.9222958
CO1.PCCNTR.9437402
CO1.PCCNTR.9450405
CO1.PCCNTR.9460748
CO1.PCCNTR.9462063
CO1.PCCNTR.9430119
CO1.PCCNTR.9421300
CO1.PCCNTR.9420502
CO1.PCCNTR.9420301
CO1.PCCNTR.9421240
CO1.PCCNTR.9374474
CO1.PCCNTR.9420318
CO1.PCCNTR.9420219
CO1.PCCNTR.9422181
CO1.PCCNTR.9461399
CO1.PCCNTR.9420223
CO1.PCCNTR.9419903
CO1.PCCNTR.9429918
CO1.PCCNTR.9422474
CO1.PCCNTR.9455170
CO1.PCCNTR.9461253
CO1.PCCNTR.9457331
CO1.PCCNTR.9419483
CO1.PCCNTR.9461246
CO1.PCCNTR.9435695
CO1.PCCNTR.9454749
CO1.PCCNTR.9423213
CO1.PCCNTR.9420323
CO1.PCCNTR.9456040
CO1.PCCNTR.9453784
CO1.PCCNTR.9420329
CO1.PCCNTR.9420215
CO1.PCCNTR.9428388
CO1.PCCNTR.9423218
CO1.PCCNTR.9460601
CO1.PCCNTR.9455429
CO1.PCCNTR.9461367
CO1.PCCNTR.9460783
CO1.PCCNTR.9461240
CO1.PCCNTR.9398556
CO1.PCCNTR.9459322
CO1.PCCNTR.9462121
CO1.PCCNTR.9418489
CO1.PCCNTR.9378514
CO1.PCCNTR.9461212
CO1.PCCNTR.9420330
CO1.PCCNTR.9258029
CO1.PCCNTR.9454772
CO1.PCCNTR.9419654
CO1.PCCNTR.9420332
CO1.PCCNTR.9461381
CO1.PCCNTR.9421088
CO1.PCCNTR.9420308
CO1.PCCNTR.9460804
CO1.PCCNTR.9420208
CO1.PCCNTR.9461304
CO1.PCCNTR.9421091
CO1.PCCNTR.9437412
CO1.PCCNTR.9455012
CO1.PCCNTR.9429917
CO1.PCCNTR.9457660
CO1.PCCNTR.9462308
CO1.PCCNTR.9460782
CO1.PCCNTR.9437603
CO1.PCCNTR.9420221
CO1.PCCNTR.9365303
CO1.PCCNTR.9419356
CO1.PCCNTR.9457668
CO1.PCCNTR.9443805
CO1.PCCNTR.9419480
CO1.PCCNTR.9435304
CO1.PCCNTR.9459407
CO1.PCCNTR.9417031
CO1.PCCNTR.9459314
CO1.PCCNTR.9420216
CO1.PCCNTR.9420303
CO1.PCCNTR.9427805
CO1.PCCNTR.9420897
CO1.PCCNTR.9422105
CO1.PCCNTR.9420856
CO1.PCCNTR.9438117
CO1.PCCNTR.9428190
CO1.PCCNTR.9419641
CO1.PCCNTR.9457355
CO1.PCCNTR.9413169
CO1.PCCNTR.9458567
CO1.PCCNTR.9436734
CO1.PCCNTR.9419663
CO1.PCCNTR.9458612
CO1.PCCNTR.9431646
CO1.PCCNTR.9430213
CO1.PCCNTR.9425401
CO1.PCCNTR.9431633
CO1.PCCNTR.9419832
CO1.PCCNTR.9420304
CO1.PCCNTR.9420321
CO1.PCCNTR.9455057
CO1.PCCNTR.9419851
CO1.PCCNTR.9461343
CO1.PCCNTR.3029181
CO1.PCCNTR.3029181
CO1.PCCNTR.9273556
CO1.PCCNTR.9258029
CO1.PCCNTR.9365303
CO1.PCCNTR.9399662
CO1.PCCNTR.9374474
CO1.PCCNTR.9413169
CO1.PCCNTR.9414611
CO1.PCCNTR.9413743
CO1.PCCNTR.9417031
CO1.PCCNTR.9422203
CO1.PCCNTR.9420897
CO1.PCCNTR.9421300
CO1.PCCNTR.9421091
CO1.PCCNTR.9422105
CO1.PCCNTR.9425401
CO1.PCCNTR.9427811
CO1.PCCNTR.9425884
CO1.PCCNTR.9428745
CO1.PCCNTR.9428190
CO1.PCCNTR.9419654
CO1.PCCNTR.9422474
CO1.PCCNTR.9421966
CO1.PCCNTR.9422074
CO1.PCCNTR.9420332
CO1.PCCNTR.9420304
CO1.PCCNTR.9420856
CO1.PCCNTR.9420876
CO1.PCCNTR.9420221
CO1.PCCNTR.9423213
CO1.PCCNTR.9420223
CO1.PCCNTR.9420219
CO1.PCCNTR.9422479
CO1.PCCNTR.9420327
CO1.PCCNTR.9420325
CO1.PCCNTR.9422181
CO1.PCCNTR.9419911
CO1.PCCNTR.9419352
CO1.PCCNTR.9420330
CO1.PCCNTR.9419903
CO1.PCCNTR.9419663
CO1.PCCNTR.9431633
CO1.PCCNTR.9419483
CO1.PCCNTR.9432011
CO1.PCCNTR.9419849
CO1.PCCNTR.9422273
CO1.PCCNTR.9419832
CO1.PCCNTR.9420216
CO1.PCCNTR.9420862
CO1.PCCNTR.9420301
CO1.PCCNTR.9420303
CO1.PCCNTR.9420318
CO1.PCCNTR.9419364
CO1.PCCNTR.9419486
CO1.PCCNTR.9422070
CO1.PCCNTR.9420314
CO1.PCCNTR.9420329
CO1.PCCNTR.9419356
CO1.PCCNTR.9420321
CO1.PCCNTR.9421264
CO1.PCCNTR.9421240
CO1.PCCNTR.9422175
CO1.PCCNTR.9419641
CO1.PCCNTR.9419480
CO1.PCCNTR.9419851
CO1.PCCNTR.9420308
CO1.PCCNTR.9419639
CO1.PCCNTR.9420406
CO1.PCCNTR.9420334
CO1.PCCNTR.9420323
CO1.PCCNTR.9420208
CO1.PCCNTR.9421134
CO1.PCCNTR.9422266
CO1.PCCNTR.9420322
CO1.PCCNTR.9420215
CO1.PCCNTR.9420206
CO1.PCCNTR.9420502
CO1.PCCNTR.9428388
CO1.PCCNTR.9436434
CO1.PCCNTR.9436734
CO1.PCCNTR.9423218
CO1.PCCNTR.9435695
CO1.PCCNTR.9437603
CO1.PCCNTR.9437402
CO1.PCCNTR.9437412
CO1.PCCNTR.9431646
CO1.PCCNTR.9437411
CO1.PCCNTR.9421088
CO1.PCCNTR.9435774
CO1.PCCNTR.9438117
CO1.PCCNTR.9430135
CO1.PCCNTR.9430213
CO1.PCCNTR.9429918
CO1.PCCNTR.9429917
CO1.PCCNTR.9430119
CO1.PCCNTR.9455012
CO1.PCCNTR.9455439
CO1.PCCNTR.9443805
CO1.PCCNTR.9455429
CO1.PCCNTR.9454772
CO1.PCCNTR.9457331
CO1.PCCNTR.9457660
CO1.PCCNTR.9453901
CO1.PCCNTR.9418489
CO1.PCCNTR.9458567
CO1.PCCNTR.9457335
CO1.PCCNTR.9457332
CO1.PCCNTR.9457668
CO1.PCCNTR.9457355
CO1.PCCNTR.9457342
CO1.PCCNTR.9222958
CO1.PCCNTR.9461265
CO1.PCCNTR.9454749
CO1.PCCNTR.9440009
CO1.PCCNTR.9456040
CO1.PCCNTR.9459322
CO1.PCCNTR.9460783
CO1.PCCNTR.9455170
CO1.PCCNTR.9457779
CO1.PCCNTR.9462308
CO1.PCCNTR.9461246
CO1.PCCNTR.9460834
CO1.PCCNTR.9460601
CO1.PCCNTR.9462121
CO1.PCCNTR.9455057
CO1.PCCNTR.9460828
CO1.PCCNTR.9453784
CO1.PCCNTR.9450405
CO1.PCCNTR.9461367
CO1.PCCNTR.9461212
CO1.PCCNTR.9460716
CO1.PCCNTR.9462063
CO1.PCCNTR.9461240
CO1.PCCNTR.9461324
CO1.PCCNTR.9453926
CO1.PCCNTR.9459314
CO1.PCCNTR.9460962
CO1.PCCNTR.9461343
CO1.PCCNTR.9378514
CO1.PCCNTR.9461381
CO1.PCCNTR.9435304
CO1.PCCNTR.9459407
CO1.PCCNTR.9460782
CO1.PCCNTR.9461304
CO1.PCCNTR.9460748
CO1.PCCNTR.9461253
CO1.PCCNTR.9427805
CO1.PCCNTR.9461391
CO1.PCCNTR.9458612
CO1.PCCNTR.9446585
CO1.PCCNTR.9461399
CO1.PCCNTR.9398556
CO1.PCCNTR.9460804

In [62]:
df_list = []

for contrato in contratos_duplicados_series.itertuples():
    df_list.append(pd.DataFrame(duckdb.query(f"""
    SELECT *
    FROM '../data/raw/**/*.parquet'
    WHERE id_contrato = '{contrato.id_contrato}'
    """).df()))
    print(f"Contrato {contrato} añadido a la lista")
contratos_duplicados = pd.concat(df_list, ignore_index=True)

Contrato Pandas(Index=0, id_contrato='CO1.PCCNTR.9422175') añadido a la lista
Contrato Pandas(Index=1, id_contrato='CO1.PCCNTR.9414611') añadido a la lista
Contrato Pandas(Index=2, id_contrato='CO1.PCCNTR.9420206') añadido a la lista
Contrato Pandas(Index=3, id_contrato='CO1.PCCNTR.9460834') añadido a la lista
Contrato Pandas(Index=4, id_contrato='CO1.PCCNTR.9273556') añadido a la lista
Contrato Pandas(Index=5, id_contrato='CO1.PCCNTR.9446585') añadido a la lista
Contrato Pandas(Index=6, id_contrato='CO1.PCCNTR.9420327') añadido a la lista
Contrato Pandas(Index=7, id_contrato='CO1.PCCNTR.9457332') añadido a la lista
Contrato Pandas(Index=8, id_contrato='CO1.PCCNTR.9419364') añadido a la lista
Contrato Pandas(Index=9, id_contrato='CO1.PCCNTR.9399662') añadido a la lista
Contrato Pandas(Index=10, id_contrato='CO1.PCCNTR.9422273') añadido a la lista
Contrato Pandas(Index=11, id_contrato='CO1.PCCNTR.9430135') añadido a la lista
Contrato Pandas(Index=12, id_contrato='CO1.PCCNTR.9419486') añadido a la lista
Contrato Pandas(Index=13, id_contrato='CO1.PCCNTR.9440009') añadido a la lista
Contrato Pandas(Index=14, id_contrato='CO1.PCCNTR.9457342') añadido a la lista
Contrato Pandas(Index=15, id_contrato='CO1.PCCNTR.9457779') añadido a la lista
Contrato Pandas(Index=16, id_contrato='CO1.PCCNTR.9421134') añadido a la lista
Contrato Pandas(Index=17, id_contrato='CO1.PCCNTR.9461391') añadido a la lista
Contrato Pandas(Index=18, id_contrato='CO1.PCCNTR.9422203') añadido a la lista
Contrato Pandas(Index=19, id_contrato='CO1.PCCNTR.9420325') añadido a la lista
Contrato Pandas(Index=20, id_contrato='CO1.PCCNTR.9422070') añadido a la lista
Contrato Pandas(Index=21, id_contrato='CO1.PCCNTR.9419639') añadido a la lista
Contrato Pandas(Index=22, id_contrato='CO1.PCCNTR.9413743') añadido a la lista
Contrato Pandas(Index=23, id_contrato='CO1.PCCNTR.9425884') añadido a la lista
Contrato Pandas(Index=24, id_contrato='CO1.PCCNTR.9420322') añadido a la lista
Contrato Pandas(Index=25, id_contrato='CO1.PCCNTR.9419352') añadido a la lista
Contrato Pandas(Index=26, id_contrato='CO1.PCCNTR.9422074') añadido a la lista
Contrato Pandas(Index=27, id_contrato='CO1.PCCNTR.9461265') añadido a la lista
Contrato Pandas(Index=28, id_contrato='CO1.PCCNTR.9437411') añadido a la lista
Contrato Pandas(Index=29, id_contrato='CO1.PCCNTR.9460962') añadido a la lista
Contrato Pandas(Index=30, id_contrato='CO1.PCCNTR.9460828') añadido a la lista
Contrato Pandas(Index=31, id_contrato='CO1.PCCNTR.9453901') añadido a la lista
Contrato Pandas(Index=32, id_contrato='CO1.PCCNTR.9421264') añadido a la lista
Contrato Pandas(Index=33, id_contrato='CO1.PCCNTR.9427811') añadido a la lista
Contrato Pandas(Index=34, id_contrato='CO1.PCCNTR.9436434') añadido a la lista
Contrato Pandas(Index=35, id_contrato='CO1.PCCNTR.9422479') añadido a la lista
Contrato Pandas(Index=36, id_contrato='CO1.PCCNTR.9428745') añadido a la lista
Contrato Pandas(Index=37, id_contrato='CO1.PCCNTR.9457335') añadido a la lista
Contrato Pandas(Index=38, id_contrato='CO1.PCCNTR.9453926') añadido a la lista
Contrato Pandas(Index=39, id_contrato='CO1.PCCNTR.9419849') añadido a la lista
Contrato Pandas(Index=40, id_contrato='CO1.PCCNTR.9460716') añadido a la lista
Contrato Pandas(Index=41, id_contrato='CO1.PCCNTR.9432011') añadido a la lista
Contrato Pandas(Index=42, id_contrato='CO1.PCCNTR.9420876') añadido a la lista
Contrato Pandas(Index=43, id_contrato='CO1.PCCNTR.9420406') añadido a la lista
Contrato Pandas(Index=44, id_contrato='CO1.PCCNTR.9455439') añadido a la lista
Contrato Pandas(Index=45, id_contrato='CO1.PCCNTR.9420334') añadido a la lista
Contrato Pandas(Index=46, id_contrato='CO1.PCCNTR.9420862') añadido a la lista
Contrato Pandas(Index=47, id_contrato='CO1.PCCNTR.9420314') añadido a la lista
Contrato Pandas(Index=48, id_contrato='CO1.PCCNTR.9421966') añadido a la lista
Contrato Pandas(Index=49, id_contrato='CO1.PCCNTR.9419911') añadido a la lista
Contrato Pandas(Index=50, id_contrato='CO1.PCCNTR.9435774') añadido a la lista
Contrato Pandas(Index=51, id_contrato='CO1.PCCNTR.9461324') añadido a la lista
Contrato Pandas(Index=52, id_contrato='CO1.PCCNTR.9422266') añadido a la lista
Contrato Pandas(Index=53, id_contrato='CO1.PCCNTR.9222958') añadido a la lista
Contrato Pandas(Index=54, id_contrato='CO1.PCCNTR.9437402') añadido a la lista
Contrato Pandas(Index=55, id_contrato='CO1.PCCNTR.9450405') añadido a la lista
Contrato Pandas(Index=56, id_contrato='CO1.PCCNTR.9460748') añadido a la lista
Contrato Pandas(Index=57, id_contrato='CO1.PCCNTR.9462063') añadido a la lista
Contrato Pandas(Index=58, id_contrato='CO1.PCCNTR.9430119') añadido a la lista
Contrato Pandas(Index=59, id_contrato='CO1.PCCNTR.9421300') añadido a la lista
Contrato Pandas(Index=60, id_contrato='CO1.PCCNTR.9420502') añadido a la lista
Contrato Pandas(Index=61, id_contrato='CO1.PCCNTR.9420301') añadido a la lista
Contrato Pandas(Index=62, id_contrato='CO1.PCCNTR.9421240') añadido a la lista
Contrato Pandas(Index=63, id_contrato='CO1.PCCNTR.9374474') añadido a la lista
Contrato Pandas(Index=64, id_contrato='CO1.PCCNTR.9420318') añadido a la lista
Contrato Pandas(Index=65, id_contrato='CO1.PCCNTR.9420219') añadido a la lista
Contrato Pandas(Index=66, id_contrato='CO1.PCCNTR.9422181') añadido a la lista
Contrato Pandas(Index=67, id_contrato='CO1.PCCNTR.9461399') añadido a la lista
Contrato Pandas(Index=68, id_contrato='CO1.PCCNTR.9420223') añadido a la lista
Contrato Pandas(Index=69, id_contrato='CO1.PCCNTR.9419903') añadido a la lista
Contrato Pandas(Index=70, id_contrato='CO1.PCCNTR.9429918') añadido a la lista
Contrato Pandas(Index=71, id_contrato='CO1.PCCNTR.9422474') añadido a la lista
Contrato Pandas(Index=72, id_contrato='CO1.PCCNTR.9455170') añadido a la lista
Contrato Pandas(Index=73, id_contrato='CO1.PCCNTR.9461253') añadido a la lista
Contrato Pandas(Index=74, id_contrato='CO1.PCCNTR.9457331') añadido a la lista
Contrato Pandas(Index=75, id_contrato='CO1.PCCNTR.9419483') añadido a la lista
Contrato Pandas(Index=76, id_contrato='CO1.PCCNTR.9461246') añadido a la lista
Contrato Pandas(Index=77, id_contrato='CO1.PCCNTR.9435695') añadido a la lista
Contrato Pandas(Index=78, id_contrato='CO1.PCCNTR.9454749') añadido a la lista
Contrato Pandas(Index=79, id_contrato='CO1.PCCNTR.9423213') añadido a la lista
Contrato Pandas(Index=80, id_contrato='CO1.PCCNTR.9420323') añadido a la lista
Contrato Pandas(Index=81, id_contrato='CO1.PCCNTR.9456040') añadido a la lista
Contrato Pandas(Index=82, id_contrato='CO1.PCCNTR.9453784') añadido a la lista
Contrato Pandas(Index=83, id_contrato='CO1.PCCNTR.9420329') añadido a la lista
Contrato Pandas(Index=84, id_contrato='CO1.PCCNTR.9420215') añadido a la lista
Contrato Pandas(Index=85, id_contrato='CO1.PCCNTR.9428388') añadido a la lista
Contrato Pandas(Index=86, id_contrato='CO1.PCCNTR.9423218') añadido a la lista
Contrato Pandas(Index=87, id_contrato='CO1.PCCNTR.9460601') añadido a la lista
Contrato Pandas(Index=88, id_contrato='CO1.PCCNTR.9455429') añadido a la lista
Contrato Pandas(Index=89, id_contrato='CO1.PCCNTR.9461367') añadido a la lista
Contrato Pandas(Index=90, id_contrato='CO1.PCCNTR.9460783') añadido a la lista
Contrato Pandas(Index=91, id_contrato='CO1.PCCNTR.9461240') añadido a la lista
Contrato Pandas(Index=92, id_contrato='CO1.PCCNTR.9398556') añadido a la lista
Contrato Pandas(Index=93, id_contrato='CO1.PCCNTR.9459322') añadido a la lista
Contrato Pandas(Index=94, id_contrato='CO1.PCCNTR.9462121') añadido a la lista
Contrato Pandas(Index=95, id_contrato='CO1.PCCNTR.9418489') añadido a la lista
Contrato Pandas(Index=96, id_contrato='CO1.PCCNTR.9378514') añadido a la lista
Contrato Pandas(Index=97, id_contrato='CO1.PCCNTR.9461212') añadido a la lista
Contrato Pandas(Index=98, id_contrato='CO1.PCCNTR.9420330') añadido a la lista
Contrato Pandas(Index=99, id_contrato='CO1.PCCNTR.9258029') añadido a la lista
Contrato Pandas(Index=100, id_contrato='CO1.PCCNTR.9454772') añadido a la lista
Contrato Pandas(Index=101, id_contrato='CO1.PCCNTR.9419654') añadido a la lista
Contrato Pandas(Index=102, id_contrato='CO1.PCCNTR.9420332') añadido a la lista
Contrato Pandas(Index=103, id_contrato='CO1.PCCNTR.9461381') añadido a la lista
Contrato Pandas(Index=104, id_contrato='CO1.PCCNTR.9421088') añadido a la lista
Contrato Pandas(Index=105, id_contrato='CO1.PCCNTR.9420308') añadido a la lista
Contrato Pandas(Index=106, id_contrato='CO1.PCCNTR.9460804') añadido a la lista
Contrato Pandas(Index=107, id_contrato='CO1.PCCNTR.9420208') añadido a la lista
Contrato Pandas(Index=108, id_contrato='CO1.PCCNTR.9461304') añadido a la lista
Contrato Pandas(Index=109, id_contrato='CO1.PCCNTR.9421091') añadido a la lista
Contrato Pandas(Index=110, id_contrato='CO1.PCCNTR.9437412') añadido a la lista
Contrato Pandas(Index=111, id_contrato='CO1.PCCNTR.9455012') añadido a la lista
Contrato Pandas(Index=112, id_contrato='CO1.PCCNTR.9429917') añadido a la lista
Contrato Pandas(Index=113, id_contrato='CO1.PCCNTR.9457660') añadido a la lista
Contrato Pandas(Index=114, id_contrato='CO1.PCCNTR.9462308') añadido a la lista
Contrato Pandas(Index=115, id_contrato='CO1.PCCNTR.9460782') añadido a la lista
Contrato Pandas(Index=116, id_contrato='CO1.PCCNTR.9437603') añadido a la lista
Contrato Pandas(Index=117, id_contrato='CO1.PCCNTR.9420221') añadido a la lista
Contrato Pandas(Index=118, id_contrato='CO1.PCCNTR.9365303') añadido a la lista
Contrato Pandas(Index=119, id_contrato='CO1.PCCNTR.9419356') añadido a la lista
Contrato Pandas(Index=120, id_contrato='CO1.PCCNTR.9457668') añadido a la lista
Contrato Pandas(Index=121, id_contrato='CO1.PCCNTR.9443805') añadido a la lista
Contrato Pandas(Index=122, id_contrato='CO1.PCCNTR.9419480') añadido a la lista
Contrato Pandas(Index=123, id_contrato='CO1.PCCNTR.9435304') añadido a la lista
Contrato Pandas(Index=124, id_contrato='CO1.PCCNTR.9459407') añadido a la lista
Contrato Pandas(Index=125, id_contrato='CO1.PCCNTR.9417031') añadido a la lista
Contrato Pandas(Index=126, id_contrato='CO1.PCCNTR.9459314') añadido a la lista
Contrato Pandas(Index=127, id_contrato='CO1.PCCNTR.9420216') añadido a la lista
Contrato Pandas(Index=128, id_contrato='CO1.PCCNTR.9420303') añadido a la lista
Contrato Pandas(Index=129, id_contrato='CO1.PCCNTR.9427805') añadido a la lista
Contrato Pandas(Index=130, id_contrato='CO1.PCCNTR.9420897') añadido a la lista
Contrato Pandas(Index=131, id_contrato='CO1.PCCNTR.9422105') añadido a la lista
Contrato Pandas(Index=132, id_contrato='CO1.PCCNTR.9420856') añadido a la lista
Contrato Pandas(Index=133, id_contrato='CO1.PCCNTR.9438117') añadido a la lista
Contrato Pandas(Index=134, id_contrato='CO1.PCCNTR.9428190') añadido a la lista
Contrato Pandas(Index=135, id_contrato='CO1.PCCNTR.9419641') añadido a la lista
Contrato Pandas(Index=136, id_contrato='CO1.PCCNTR.9457355') añadido a la lista
Contrato Pandas(Index=137, id_contrato='CO1.PCCNTR.9413169') añadido a la lista
Contrato Pandas(Index=138, id_contrato='CO1.PCCNTR.9458567') añadido a la lista
Contrato Pandas(Index=139, id_contrato='CO1.PCCNTR.9436734') añadido a la lista
Contrato Pandas(Index=140, id_contrato='CO1.PCCNTR.9419663') añadido a la lista
Contrato Pandas(Index=141, id_contrato='CO1.PCCNTR.9458612') añadido a la lista
Contrato Pandas(Index=142, id_contrato='CO1.PCCNTR.9431646') añadido a la lista
Contrato Pandas(Index=143, id_contrato='CO1.PCCNTR.9430213') añadido a la lista
Contrato Pandas(Index=144, id_contrato='CO1.PCCNTR.9425401') añadido a la lista
Contrato Pandas(Index=145, id_contrato='CO1.PCCNTR.9431633') añadido a la lista
Contrato Pandas(Index=146, id_contrato='CO1.PCCNTR.9419832') añadido a la lista
Contrato Pandas(Index=147, id_contrato='CO1.PCCNTR.9420304') añadido a la lista
Contrato Pandas(Index=148, id_contrato='CO1.PCCNTR.9420321') añadido a la lista
Contrato Pandas(Index=149, id_contrato='CO1.PCCNTR.9455057') añadido a la lista
Contrato Pandas(Index=150, id_contrato='CO1.PCCNTR.9419851') añadido a la lista
Contrato Pandas(Index=151, id_contrato='CO1.PCCNTR.9461343') añadido a la lista
Contrato Pandas(Index=152, id_contrato='CO1.PCCNTR.3029181') añadido a la lista
Contrato Pandas(Index=153, id_contrato='CO1.PCCNTR.3029181') añadido a la lista
Contrato Pandas(Index=154, id_contrato='CO1.PCCNTR.9273556') añadido a la lista
Contrato Pandas(Index=155, id_contrato='CO1.PCCNTR.9258029') añadido a la lista
Contrato Pandas(Index=156, id_contrato='CO1.PCCNTR.9365303') añadido a la lista
Contrato Pandas(Index=157, id_contrato='CO1.PCCNTR.9399662') añadido a la lista
Contrato Pandas(Index=158, id_contrato='CO1.PCCNTR.9374474') añadido a la lista
Contrato Pandas(Index=159, id_contrato='CO1.PCCNTR.9413169') añadido a la lista
Contrato Pandas(Index=160, id_contrato='CO1.PCCNTR.9414611') añadido a la lista
Contrato Pandas(Index=161, id_contrato='CO1.PCCNTR.9413743') añadido a la lista
Contrato Pandas(Index=162, id_contrato='CO1.PCCNTR.9417031') añadido a la lista
Contrato Pandas(Index=163, id_contrato='CO1.PCCNTR.9422203') añadido a la lista
Contrato Pandas(Index=164, id_contrato='CO1.PCCNTR.9420897') añadido a la lista
Contrato Pandas(Index=165, id_contrato='CO1.PCCNTR.9421300') añadido a la lista
Contrato Pandas(Index=166, id_contrato='CO1.PCCNTR.9421091') añadido a la lista
Contrato Pandas(Index=167, id_contrato='CO1.PCCNTR.9422105') añadido a la lista
Contrato Pandas(Index=168, id_contrato='CO1.PCCNTR.9425401') añadido a la lista
Contrato Pandas(Index=169, id_contrato='CO1.PCCNTR.9427811') añadido a la lista
Contrato Pandas(Index=170, id_contrato='CO1.PCCNTR.9425884') añadido a la lista
Contrato Pandas(Index=171, id_contrato='CO1.PCCNTR.9428745') añadido a la lista
Contrato Pandas(Index=172, id_contrato='CO1.PCCNTR.9428190') añadido a la lista
Contrato Pandas(Index=173, id_contrato='CO1.PCCNTR.9419654') añadido a la lista
Contrato Pandas(Index=174, id_contrato='CO1.PCCNTR.9422474') añadido a la lista
Contrato Pandas(Index=175, id_contrato='CO1.PCCNTR.9421966') añadido a la lista
Contrato Pandas(Index=176, id_contrato='CO1.PCCNTR.9422074') añadido a la lista
Contrato Pandas(Index=177, id_contrato='CO1.PCCNTR.9420332') añadido a la lista
Contrato Pandas(Index=178, id_contrato='CO1.PCCNTR.9420304') añadido a la lista
Contrato Pandas(Index=179, id_contrato='CO1.PCCNTR.9420856') añadido a la lista
Contrato Pandas(Index=180, id_contrato='CO1.PCCNTR.9420876') añadido a la lista
Contrato Pandas(Index=181, id_contrato='CO1.PCCNTR.9420221') añadido a la lista
Contrato Pandas(Index=182, id_contrato='CO1.PCCNTR.9423213') añadido a la lista
Contrato Pandas(Index=183, id_contrato='CO1.PCCNTR.9420223') añadido a la lista
Contrato Pandas(Index=184, id_contrato='CO1.PCCNTR.9420219') añadido a la lista
Contrato Pandas(Index=185, id_contrato='CO1.PCCNTR.9422479') añadido a la lista
Contrato Pandas(Index=186, id_contrato='CO1.PCCNTR.9420327') añadido a la lista
Contrato Pandas(Index=187, id_contrato='CO1.PCCNTR.9420325') añadido a la lista
Contrato Pandas(Index=188, id_contrato='CO1.PCCNTR.9422181') añadido a la lista
Contrato Pandas(Index=189, id_contrato='CO1.PCCNTR.9419911') añadido a la lista
Contrato Pandas(Index=190, id_contrato='CO1.PCCNTR.9419352') añadido a la lista
Contrato Pandas(Index=191, id_contrato='CO1.PCCNTR.9420330') añadido a la lista
Contrato Pandas(Index=192, id_contrato='CO1.PCCNTR.9419903') añadido a la lista
Contrato Pandas(Index=193, id_contrato='CO1.PCCNTR.9419663') añadido a la lista
Contrato Pandas(Index=194, id_contrato='CO1.PCCNTR.9431633') añadido a la lista
Contrato Pandas(Index=195, id_contrato='CO1.PCCNTR.9419483') añadido a la lista
Contrato Pandas(Index=196, id_contrato='CO1.PCCNTR.9432011') añadido a la lista
Contrato Pandas(Index=197, id_contrato='CO1.PCCNTR.9419849') añadido a la lista
Contrato Pandas(Index=198, id_contrato='CO1.PCCNTR.9422273') añadido a la lista
Contrato Pandas(Index=199, id_contrato='CO1.PCCNTR.9419832') añadido a la lista
Contrato Pandas(Index=200, id_contrato='CO1.PCCNTR.9420216') añadido a la lista
Contrato Pandas(Index=201, id_contrato='CO1.PCCNTR.9420862') añadido a la lista
Contrato Pandas(Index=202, id_contrato='CO1.PCCNTR.9420301') añadido a la lista
Contrato Pandas(Index=203, id_contrato='CO1.PCCNTR.9420303') añadido a la lista
Contrato Pandas(Index=204, id_contrato='CO1.PCCNTR.9420318') añadido a la lista
Contrato Pandas(Index=205, id_contrato='CO1.PCCNTR.9419364') añadido a la lista
Contrato Pandas(Index=206, id_contrato='CO1.PCCNTR.9419486') añadido a la lista
Contrato Pandas(Index=207, id_contrato='CO1.PCCNTR.9422070') añadido a la lista
Contrato Pandas(Index=208, id_contrato='CO1.PCCNTR.9420314') añadido a la lista
Contrato Pandas(Index=209, id_contrato='CO1.PCCNTR.9420329') añadido a la lista
Contrato Pandas(Index=210, id_contrato='CO1.PCCNTR.9419356') añadido a la lista
Contrato Pandas(Index=211, id_contrato='CO1.PCCNTR.9420321') añadido a la lista
Contrato Pandas(Index=212, id_contrato='CO1.PCCNTR.9421264') añadido a la lista
Contrato Pandas(Index=213, id_contrato='CO1.PCCNTR.9421240') añadido a la lista
Contrato Pandas(Index=214, id_contrato='CO1.PCCNTR.9422175') añadido a la lista
Contrato Pandas(Index=215, id_contrato='CO1.PCCNTR.9419641') añadido a la lista
Contrato Pandas(Index=216, id_contrato='CO1.PCCNTR.9419480') añadido a la lista
Contrato Pandas(Index=217, id_contrato='CO1.PCCNTR.9419851') añadido a la lista
Contrato Pandas(Index=218, id_contrato='CO1.PCCNTR.9420308') añadido a la lista
Contrato Pandas(Index=219, id_contrato='CO1.PCCNTR.9419639') añadido a la lista
Contrato Pandas(Index=220, id_contrato='CO1.PCCNTR.9420406') añadido a la lista
Contrato Pandas(Index=221, id_contrato='CO1.PCCNTR.9420334') añadido a la lista
Contrato Pandas(Index=222, id_contrato='CO1.PCCNTR.9420323') añadido a la lista
Contrato Pandas(Index=223, id_contrato='CO1.PCCNTR.9420208') añadido a la lista
Contrato Pandas(Index=224, id_contrato='CO1.PCCNTR.9421134') añadido a la lista
Contrato Pandas(Index=225, id_contrato='CO1.PCCNTR.9422266') añadido a la lista
Contrato Pandas(Index=226, id_contrato='CO1.PCCNTR.9420322') añadido a la lista
Contrato Pandas(Index=227, id_contrato='CO1.PCCNTR.9420215') añadido a la lista
Contrato Pandas(Index=228, id_contrato='CO1.PCCNTR.9420206') añadido a la lista
Contrato Pandas(Index=229, id_contrato='CO1.PCCNTR.9420502') añadido a la lista
Contrato Pandas(Index=230, id_contrato='CO1.PCCNTR.9428388') añadido a la lista
Contrato Pandas(Index=231, id_contrato='CO1.PCCNTR.9436434') añadido a la lista
Contrato Pandas(Index=232, id_contrato='CO1.PCCNTR.9436734') añadido a la lista
Contrato Pandas(Index=233, id_contrato='CO1.PCCNTR.9423218') añadido a la lista
Contrato Pandas(Index=234, id_contrato='CO1.PCCNTR.9435695') añadido a la lista
Contrato Pandas(Index=235, id_contrato='CO1.PCCNTR.9437603') añadido a la lista
Contrato Pandas(Index=236, id_contrato='CO1.PCCNTR.9437402') añadido a la lista
Contrato Pandas(Index=237, id_contrato='CO1.PCCNTR.9437412') añadido a la lista
Contrato Pandas(Index=238, id_contrato='CO1.PCCNTR.9431646') añadido a la lista
Contrato Pandas(Index=239, id_contrato='CO1.PCCNTR.9437411') añadido a la lista
Contrato Pandas(Index=240, id_contrato='CO1.PCCNTR.9421088') añadido a la lista
Contrato Pandas(Index=241, id_contrato='CO1.PCCNTR.9435774') añadido a la lista
Contrato Pandas(Index=242, id_contrato='CO1.PCCNTR.9438117') añadido a la lista
Contrato Pandas(Index=243, id_contrato='CO1.PCCNTR.9430135') añadido a la lista
Contrato Pandas(Index=244, id_contrato='CO1.PCCNTR.9430213') añadido a la lista
Contrato Pandas(Index=245, id_contrato='CO1.PCCNTR.9429918') añadido a la lista
Contrato Pandas(Index=246, id_contrato='CO1.PCCNTR.9429917') añadido a la lista
Contrato Pandas(Index=247, id_contrato='CO1.PCCNTR.9430119') añadido a la lista
Contrato Pandas(Index=248, id_contrato='CO1.PCCNTR.9455012') añadido a la lista
Contrato Pandas(Index=249, id_contrato='CO1.PCCNTR.9455439') añadido a la lista
Contrato Pandas(Index=250, id_contrato='CO1.PCCNTR.9443805') añadido a la lista

In [64]:
contratos_duplicados.to_excel("contratos_duplicados.xlsx", index= False)